language: node_js
node_js:
  - '12'
branches:
  only:
    - master
    - develop
    - '/^v.*$/'
before_script:
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    edge: true
    skip_cleanup: true
    api_key:
      secure: jWx66cCnI4kzeq5F1XbkwyXm6ecWxB9Xt3TpmE8csh3U6Tk634bDySKZM1WHwbBmMiLkA03j+zAADLghIICrz+Al4Ns2bX1KAjNPBEjv4a9DhDpBb3aXqK7waXslqlHOm29stRjfL/jhZxWyB1G6qNRoaL3fF32Iq9XLVDlOWKAa1fAt74EixZhb2xCZlzkPPr+SRYwlKwCZ0o0LIAjwssSL2irgv60Ag/vAVIyv8ysisxftWznte/T5l6ZM6TnXLWH/qplWt/K/NsAK6msyTCM1PBRVogyrZi/pizyQFIRMxkdV9KxF1yqV7GUruOvUHGZiW4gqfTKVet5XKOiilYknlP6GNChZktyeORf7V5drayz9AvE0o2MlIdkfYJEijol0a6RwlF+N00QlTAwrRUcIRs4vUzcDg2un5zLBKqzpWpFXsWYyN42yaBv4UdrUR6EZ8wBx09oHFsdVXVoRODMCDjkyOkTba+w9fkRVtGMBIekvSo10OMPPVYvyJQE+gq5rBPQKYsOUaWKAV6/pmIe+f3DOC3f27llZFHbIgeEBYwxvrXIOmW8ig50dNh/DSqdx3WJNWdrEEgUMwnkP68rKMr7q35d/Qanp5QICTQ84onJBAMTKjTfA7nKB3n7Ko7xfH5/VnGIXY08xNK4n/6feNmY/tP85XXqPuz3s6go=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/higlass-svelte
  - provider: npm
    edge: true
    skip_cleanup: true
    email: code@lekschas.de
    api_key:
      secure: uCJS47dnu/sX4nAoGD+wahAwFHO9va/Z/Etqa2Ei7ZGx8Zu3UeyWw1Qn3yhyky6VH2Wv59Y01aEE8YWz3QqIgcjT6PUxB67keYpa9YxUL0hWlSJavNAYrYWD5NvXHNJLbfqroryo1LEUOGk1V0lpTQZUylPZm/mkCpzvE4g5yxl62uUfoe7Ssn7vzSJdrxpTnQtgrFfHTRZ9xCzdNK2hPmURCW4nkmx/p1x6+in8z8PlhQDsnussb8BiDz3VPalJo3xqvYQcWZQ1bjpnjYYfZRc6BdtusuaPv/5CisShXIJRINwXLy4ILNXTAm++0zSBAz794yKhVgV37zTbtWzM44ZvjJCSs0xL1ddh6/Hhl+SArlcF2NDiKe/pfzAUhQ1y6SP4Y/4paJX172QW+sx+ZLUTf+v+vwW0wkuutjAFyBXECrq/e/k9ailuk2v/Ne1QQYPiq/1UmUesFiOk3CWsWC8Gf3pHcz6jgv1IjwaKltvjsLzYTbllbn6KTiFK9oad4lS4quXROK5Bgb4xGFr3lQYXTGd2cCLjac59cqP6wktS/lj8IsU46C7nQuHNfQ2xUbyOCb6b+gTtq293YRTVwREwtySgJCp2ygzg7/QZOhA1wdZbgY1mNQsfAPP0nEbz/N3EGoHKVZaQgxKlcGioCULz48h/3C5gGHfZ2MOOuMc=
    on:
      branch: master
      tags: true
      repo: flekschas/higlass-svelte
